version: '3.5'

services:
  mda:
    ports:
      - "0.0.0.0:143:143"
      - "0.0.0.0:993:993"
      - "0.0.0.0:110:110"
      - "0.0.0.0:995:995"

  mta:
    ports:
      - "0.0.0.0:25:25"
      - "0.0.0.0:587:587"
    # Uncomment to use SSL encrypted mail submission
    #  - "0.0.0.0:465:465"

  web:
    # Remove this block if you are using jwilder/nginx-proxy reverse proxy
    ports:
      - "0.0.0.0:81:80"
    # Setup network to connect for reverse proxy
    # networks:
      # - networkName
